### ISSUE TITLE
Add API interaction Desmos API v1.8

### ISSUE THREAD

**Issue by Clement-Wright** [CSNSE/redoapp2#5]
Add API integration to display a graph.

**Comment by ghost** [comment]
You can give more information on your ticket -- what is the api?  where did you find it??

**Comment by Clement-Wright** [comment]
<img width="624" alt="Screenshot 2024-01-30 180611" src="https://github.com/CSNSE/redoapp2/assets/143111117/6fea297b-a40d-4eb8-aeed-5ca2fd7254b3">

Added a Graph Icon to link to Desmos.html
